#!/bin/bash

set -euo pipefail

source .venv/bin/activate
unset PYTHONPATH

# Per-apply ssh-agent. The cluster SSH key is generated by Terraform and piped
# directly into this agent (see modules/provision_server), so the key
# never lands on disk. Killed on exit so nothing is left behind.
eval "$(ssh-agent -s)" >/dev/null
trap 'ssh-agent -k >/dev/null 2>&1 || true' EXIT

# Pre-load the SSH private key from Key Vault into ssh-agent. This is what
# prevents terraform_data.ssh_agent_loaded from churning on every fresh shell:
# without this, each new agent socket is empty and the resource has to re-run
# its local-exec to install the key. With this, the agent already has the key
# by the time Terraform plans, so triggers_replace can stay stable.
#
# Best-effort: tolerated failures —
#   - First apply: the secret does not exist in Key Vault yet (it is created
#     by secrets.tf at the end of the apply). Terraform's ssh_agent_loaded
#     bootstraps the agent in that one case.
#   - No az / not logged in / no Key Vault access: also falls through to the
#     bootstrap path. If the key is also not yet in state, Ansible later
#     errors with a clear authentication failure.
vault_name="${AZURE_KEYVAULT_NAME:-}"
if [ -z "$vault_name" ] && [ -f backend.tf ]; then
  vault_name=$(sed -n '/variable "environment_name"/,/^}/ s/.*default[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' backend.tf)
fi

if [ -n "$vault_name" ] && command -v az >/dev/null 2>&1; then
  if ssh_key=$(az keyvault secret show \
        --vault-name "$vault_name" \
        --name ssh-private-key \
        --query value -o tsv 2>/dev/null) && [ -n "$ssh_key" ]; then
    printf '%s\n' "$ssh_key" | ssh-add - >/dev/null 2>&1 \
      && echo "Loaded SSH key from Key Vault $vault_name into ssh-agent"

    # Ensure Twingate resources are authenticated before Terraform touches the
    # cluster.  `twingate resources` lists each resource with an AUTH STATUS column;
    # any resource whose status does NOT contain "Auth expires" needs re-auth.
    if command -v twingate >/dev/null 2>&1; then
      while IFS= read -r resource_name; do
        [ -z "$resource_name" ] && continue
        echo "Twingate resource \"$resource_name\" is not authenticated — triggering auth…"
        twingate auth "$resource_name"
      done < <(
        twingate resources 2>/dev/null \
          | tail -n +2 \
          | grep -v 'Auth expires' \
          | sed 's/\t.*//'
      )
    fi
  fi
fi


terraform plan -out=tfplan
# terraform plan -refresh-only -out=tfplan
terraform apply -auto-approve tfplan
